### PR TITLE
RetroPie menu should be hidden when not Full UI

### PR DESCRIPTION
**Pull request by Max13**

### CODE REVIEW

**Review by zigurana — COMMENTED** [review]
Hi, I am not sure I understand what you are trying to achieve with these changes. Can you explain the reason for them?
For instance, why would you only want to parse the game-list in full UI mode?

**Comment by Max13** [comment]
Hi, sorry I thought the title would be clear enough.

I think that the RetroPie menu (Bluetooth, NetPlay, RetroArch config, Wifi, ...) should not be displayed when the UI is not full. The same way some options are hidden from the "start" menu, the RetroPie menu should be hidden as well.

**Comment by zigurana** [comment]
Ah I see, I would do that via hiding the items. (by editing the metadata values for the gamelist generated for the RetroPie system).

**Comment by Max13** [comment]
I don't think it would be a logical idea.

If you edit the metadata, it means you're letting the system create them, then you parse and set them "hidden" 1 by 1. This process will take a linear time depending on the list length.

I think it's more logical to prevent the system to create the list. The process is taking a constant time to execute, no matter how long is the list (it's not impossible for it to be much longer in the future).

Sorry for my English, not my first language. What I want to say is that I don't think it's logical to edit x metadata for x items every time the UI mode is changed. What do you think ?

**Comment by zigurana** [comment]
My apologies, as you probably noticed, I am in the process of a rather extensive re-design and rewriting of Git history. I will reconsider your issue once that is over. No need to file a new PR for this at this moment.

**Pull request closed without merging**
